### ISSUE TITLE
Possibility to save sessions?

### ISSUE THREAD

**Issue by martensson** [ansd/lastpass-go#28]
Hi! I am investigating ways to use the Lastpass API and found this fork that seems like the most complete and that also supports 2FA. But is there a way for the client to save the token/session across runs? Depending on the use case, and to automate things it is a bit cumbersome having to input a new key for every run. Something similar to lastpass-cli --trust feature. Thanks! :)

**Comment by ansd** [comment]
Hey @martensson,

thanks for bringing this up. It's a good question.

> having to input a new key for every run

By "key" do you mean the master password or the 2nd factor?

If you mean the 2nd factor, I could try to add the `--trust` equivalent of the lastpass-cli to this lastpass-go library.
The `--trust` option will cause subsequent logins to not require multifactor authentication.
However it will still require you to login with the master password when creating a new client (i.e. "across runs").

**Comment by ansd** [comment]
@martensson I spiked the `--trust` feature.
Feel free to try it out and to provide feedback or suggestions how to improve it :)
It works well for me.
It's not production ready yet since tests, logging, docs, and examples are missing.

You can try it out as follows.

The 1st time you log in:
```go
client, err := lastpass.NewClient(
	context.Background(),
	"username",
	"masterpassword",
	lastpass.WithOneTimePassword("123456"),
	lastpass.WithTrust(),
)
```
This will create a new file `trusted_id` locally on your computer containing a random trust ID.
It will also add a new trusted device to your LastPass vault under `Account Settings` => `Trusted Devices`.

From then on, you can login without providing the 2nd factor:
```go
client, err := lastpass.NewClient(
	context.Background(),
	"username",
	"masterpassword",
)
```

**Comment by martensson** [comment]
Hi @ansd! Sorry for not answering you earlier, just had some busy weeks that forced me to postpone this issue. I will run some tests soon and let you know. And thanks for adding this feature, it was kind of a deal breaker for a project I am working with, specially when you want to integrate Lastpass into some CI/CD pipeline where you are unable to input a 2FA key each time. 💯

**Comment by ansd** [comment]
Hey @martensson, I finalised the "trust" feature and merged it into `master` branch.
You can find an example how to use it in https://github.com/ansd/lastpass-go/blob/master/examples/trust/example.go.
There's no rush, whenever you have more time to do some tests, let me know :)

**Comment by ansd** [comment]
This is now part of `v0.2.0`.
